### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by NouCake** [Abstractolotl/azplace-rest-backend#73]
Implement the Logout:

- Remove the Session Cookie of the User
- Invalidate the Spring Session

**Comment by Ancocodet** [comment]
https://www.baeldung.com/spring-security-session

**Comment by NouCake** [comment]
When you find out why the session still has a valid user after /auth/logout is called, please let me know.
This is the code that calls the endpoint on the frontend: 
https://github.com/Abstractolotl/azplace-frontend/blob/main/src/api.ts#L83

Found out why: https://github.com/Abstractolotl/azplace-rest-backend/pull/80/files#r989844796
